/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multi_hopper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d3646bedbd26f622516708fb82b86992)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bluetooth/multi_hopper.h>
// pydoc.h is automatically generated in the build directory
#include <multi_hopper_pydoc.h>

void bind_multi_hopper(py::module& m)
{

    using multi_hopper    = ::gr::bluetooth::multi_hopper;


    py::class_<multi_hopper, gr::bluetooth::multi_block,
        std::shared_ptr<multi_hopper>>(m, "multi_hopper", D(multi_hopper))

        .def(py::init(&multi_hopper::make),
           py::arg("sample_rate"),
           py::arg("center_freq"),
           py::arg("squelch_threshold"),
           py::arg("LAP"),
           py::arg("aliased"),
           py::arg("tun"),
           D(multi_hopper,make)
        )
        



        ;




}








