/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multi_block.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d443652e44a58f77afd083265d2103e8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bluetooth/multi_block.h>
// pydoc.h is automatically generated in the build directory
#include <multi_block_pydoc.h>

void bind_multi_block(py::module& m)
{

    using multi_block = ::gr::bluetooth::multi_block;


    py::class_<multi_block,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<multi_block>>(m, "multi_block", D(multi_block))


        .def("work",
             &multi_block::work,
             py::arg("noutput_items"),
             py::arg("input_items"),
             py::arg("output_items"),
             D(multi_block, work))

        ;
}
