#!/bin/bash

DIR=/home/dominicgs/uni/4091/svn/gnuradio/gr-bluetooth/examples

NUMBERS="bb bc bd be bf c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 ca cb cc cd ce cf d0 d1 d2 d3 d4 d5 d6 d7 d8 d9 da db dc dd de df e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 ea eb ec ed ee ef f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 fa fb fc fd fe ff"

for i in `echo $NUMBERS`
do

bccmd psset -r bdaddr 0xb3 0x00 0x5b 0x0a 0x$i 0x00 0x02 0x00

sleep 2

echo "Setting byte to $i"

l2ping -f 00:11:F6:05:9E:49 >/dev/null &

sleep 2

$DIR/bluetooth_UAP_sniffer.py -f 2421M -g 49 -l b30a5b -p 100

pkill l2ping

sleep 2

done
